name: weather_app_ddd
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  dio: ^5.8.0+1
  location: ^8.0.0
  shimmer: ^3.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.5
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
